version: 2.1

environment:
  TAG: 0.0.<< pipeline.number >>

jobs:
  test:
    docker:
      - image: python:3.12-slim-bookworm
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run test
          command: python3 ./src/test_webapp.py
  build:
    docker:
      - image: cimg/base:2024.01
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t $REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:$TAG .
            docker build -t $REGISTRY_USER/$CIRCLE_PROJECT_REPONAME .
      - run:
          name: Push Docker image
          command: |
            echo $REGISTRY_PASS | docker login -u $REGISTRY_USER --password-stdin
            docker push $REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:$TAG
            docker push $REGISTRY_USER/$CIRCLE_PROJECT_REPONAME

  deploy:
    docker:
      - image: cimg/base:2024.01
    resource_class: small
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
            docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
            docker container stop $CIRCLE_PROJECT_REPONAME || true &&
            docker container rm $CIRCLE_PROJECT_REPONAME || true &&
            docker pull $REGISTRY_USER/$CIRCLE_PROJECT_REPONAME &&
            docker run --name $CIRCLE_PROJECT_REPONAME -p 5005:5000 -d $REGISTRY_USER/$CIRCLE_PROJECT_REPONAME"


workflows:
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build